/*
    This file include all codes of subsystem Call Manager
*/
#ifndef SUBSYSCDM_H
#define SUBSYSCDM_H
#include <stdint.h>
#include "diagcmd.h"
struct CM_header
{
    const uint8_t CMD_CODE = DIAG_SUBSYS_CMD_F;
    const uint8_t SUBSYS_ID =15;
    uint16_t SUBSYS_CMD_CODE;
    uint8_t data[];
};

/* SUBSYS_CMD_CODE
 – CMLOG_STATE_INFO_F
01 – CMLOG_PLMN_LIST_REQ_F
02 – CMLOG_SYS_SEL_REQ_F
03 – CM_CDMA_CALL_ORIGINATION
04 – CM_CALL_END
05 – CM_WCDMA_CALL_ORIGINATION
06 – CM_GSM_CALL_ORIGINATION
07 – CM_GET_CALL_INFORMATION_LIST
08 – CM_SET_PASSWORD
09 – CM_SET_CLOSED_USER_GROUP_ PREFERENCE
10 – CM_GET_CLOSED_USER_GROUP_ PREFERENCE
11 – CM_SEND_USSD_REPLY
12 – CM_GET_CCM_INFO
13 - CM_SEND_SUPS_LCS_MOLR
14 - CM_SEND_SUPS_LCS_MOLR_COMPLETED
15 - CM_ORIG_THR_TBL_RESET
16 - CM_SYSTEM_SELECTION_PREFERENCE2
17 - CM_GET_CELL_SERVICE_IND
22 – CM_ECALL_CALL_ORIGINATION
23 – CM_ECALL_CALL_END
24 – CMLOG_STATE_INFO_PER_SUBS_F
25 – CMLOG_PLMN_SELECTION_MODE_PER_SUBS_REQ_F
26 – CMLOG_SYSTEM_SELECTION_PREFERENCE_PER_SUBS_REQ_F
27 – CM_WCDMA_CALL_ORIGINATION_PER_SUBS
28 – CM_GSM_CALL_ORIGINATION_PER_SUBS
29 – CM_GET_CALL_INFORMATION_LIST_PER_SUBS
30 – CM_SET_PASSWORD_PER_SUBS
31 – CM_SEND_USSD_REPLY_PER_SUBS
32 – CM_GET_CCM_INFO_PER_SUBS
33 – CM_SEND_SUPS_LCS_MOLR_PER_SUBS
34 – CM_SEND_SUPS_LCS_MOLR_COMPLETED_PER_SUBS
35 – CM_GET_CELL_SERVICE_IND_PER_SUBS
37 – CMLOG_STATE_INFO2_F
38
39 – CMLOG_SYSTEM_SELECTION_PREFERENCE2_PER_SUBS_REQ_F
40 – CM_SYSTEM_SELECTION_PREFERENCE_WITH_LTE
41 – CM_CALL_ANSWER
42 – CM_GW_CALL_SETUP_RESPONSE
43 – CM_SYSTEM_SELECTION_PREFERENCE2_PER_SUBS
44 – CM_MULTISIM_STATE_INFO
*/

#define CMLOG_STATE_INFO_F uint16_t(0)

#define CMLOG_PLMN_LIST_REQ_F uint16_t(1)

#define CMLOG_SYS_SEL_REQ_F uint16_t(2)

#define CM_CDMA_CALL_ORIGINATION uint16_t(3)

#define CM_CALL_END uint16_t(4)

#define CM_WCDMA_CALL_ORIGINATION uint16_t(5)

#define CM_GSM_CALL_ORIGINATION uint16_t(6)

#define CM_GET_CALL_INFORMATION_LIST uint16_t(7)

#define CM_SET_PASSWORD uint16_t(8)

#define CM_SET_CLOSED_USER_GROUP_ uint16_t(09)

#define CM_GET_CLOSED_USER_GROUP_ uint16_t(10)

#define CM_SEND_USSD_REPLY uint16_t(11)

#define CM_GET_CCM_INFO uint16_t(12)

#define CM_SEND_SUPS_LCS_MOLR uint16_t(13)

#define CM_SEND_SUPS_LCS_MOLR_COMPLETED uint16_t(14)

#define CM_ORIG_THR_TBL_RESET uint16_t(15)

#define CM_SYSTEM_SELECTION_PREFERENCE2 uint16_t(16)

#define CM_GET_CELL_SERVICE_IND uint16_t(17)

#define CM_ECALL_CALL_ORIGINATION uint16_t(22)

#define CM_ECALL_CALL_END uint16_t(23)

#define CMLOG_STATE_INFO_PER_SUBS_F uint16_t(24)

#define CMLOG_PLMN_SELECTION_MODE_PER_SUBS_REQ_F uint16_t(25)

#define CMLOG_SYSTEM_SELECTION_PREFERENCE_PER_SUBS_REQ_F uint16_t(26)

#define CM_WCDMA_CALL_ORIGINATION_PER_SUBS uint16_t(27)

#define CM_GSM_CALL_ORIGINATION_PER_SUBS uint16_t(28)

#define CM_GET_CALL_INFORMATION_LIST_PER_SUBS uint16_t(29)

#define CM_SET_PASSWORD_PER_SUBS uint16_t(30)

#define CM_SEND_USSD_REPLY_PER_SUBS uint16_t(31)

#define CM_GET_CCM_INFO_PER_SUBS uint16_t(32)

#define CM_SEND_SUPS_LCS_MOLR_PER_SUBS uint16_t(33)

#define CM_SEND_SUPS_LCS_MOLR_COMPLETED_PER_SUBS uint16_t(34)

#define CM_GET_CELL_SERVICE_IND_PER_SUBS uint16_t(35)

#define CMLOG_STATE_INFO2_F uint16_t(37)

#define CMLOG_SYSTEM_SELECTION_PREFERENCE2_PER_SUBS_REQ_F uint16_t(39)

#define CM_SYSTEM_SELECTION_PREFERENCE_WITH_LTE uint16_t(40)

#define CM_CALL_ANSWER uint16_t(41)

#define CM_GW_CALL_SETUP_RESPONSE uint16_t(42)

#define CM_SYSTEM_SELECTION_PREFERENCE2_PER_SUBS uint16_t(43)

#define CM_MULTISIM_STATE_INFO uint16_t(44)


#endif