#pragma once
#ifndef _GSMTAP_H_
#define _GSMTAP_H_

#define GSMTAP_TYPE_UM (uint8_t(0x01))
#define GSMTAP_TYPE_ABIS (uint8_t(0x02))
#define GSMTAP_TYPE_UMTS_RRC (uint8_t(0x0c))
#define GSMTAP_TYPE_LTE_RRC (uint8_t(0x0d))
#define GSMTAP_TYPE_LTE_NAS (uint8_t(0x12))

#define GSMTAP_CHANNEL_UNKNOWN (uint8_t(0x00))
#define GSMTAP_CHANNEL_BCCH (uint8_t(0x01))
#define GSMTAP_CHANNEL_CCCH (uint8_t(0x02))
#define GSMTAP_CHANNEL_RACH (uint8_t(0x03))
#define GSMTAP_CHANNEL_AGCH (uint8_t(0x04))
#define GSMTAP_CHANNEL_PCH (uint8_t(0x05))
#define GSMTAP_CHANNEL_SDCCH (uint8_t(0x06))
#define GSMTAP_CHANNEL_SDCCH4 (uint8_t(0x07))
#define GSMTAP_CHANNEL_SDCCH8 (uint8_t(0x08))
#define GSMTAP_CHANNEL_TCH_F (uint8_t(0x09))
#define GSMTAP_CHANNEL_TCH_H (uint8_t(0x0a))
#define GSMTAP_CHANNEL_PACCH (uint8_t(0x0b))
#define GSMTAP_CHANNEL_CBCH52 (uint8_t(0x0c))
#define GSMTAP_CHANNEL_PDTCH (uint8_t(0x0d))
#define GSMTAP_CHANNEL_PTCCH (uint8_t(0x0e))
#define GSMTAP_CHANNEL_CBCH51 (uint8_t(0x0f))

#define GSMTAP_CHANNEL_ACCH (uint8_t(0x80)) // To be combined, ACCH + SDCCH = SACCH

#define GSMTAP_RRC_SUB_DL_DCCH_Message (uint8_t(0))
#define GSMTAP_RRC_SUB_UL_DCCH_Message (uint8_t(1))
#define GSMTAP_RRC_SUB_DL_CCCH_Message (uint8_t(2))
#define GSMTAP_RRC_SUB_UL_CCCH_Message (uint8_t(3))
#define GSMTAP_RRC_SUB_PCCH_Message (uint8_t(4))
#define GSMTAP_RRC_SUB_DL_SHCCH_Message (uint8_t(5))
#define GSMTAP_RRC_SUB_UL_SHCCH_Message (uint8_t(6))
#define GSMTAP_RRC_SUB_BCCH_FACH_Message (uint8_t(7))
#define GSMTAP_RRC_SUB_BCCH_BCH_Message (uint8_t(8))
#define GSMTAP_RRC_SUB_MCCH_Message (uint8_t(9))
#define GSMTAP_RRC_SUB_MSCH_Message (uint8_t(10))
#define GSMTAP_RRC_SUB_HandoverToUTRANCommand (uint8_t(11))
#define GSMTAP_RRC_SUB_InterRATHandoverInfo (uint8_t(12))
#define GSMTAP_RRC_SUB_SystemInformation_BCH (uint8_t(13))
#define GSMTAP_RRC_SUB_System_Information_Container (uint8_t(14))
#define GSMTAP_RRC_SUB_UE_RadioAccessCapabilityInfo (uint8_t(15))
#define GSMTAP_RRC_SUB_MasterInformationBlock (uint8_t(16))
#define GSMTAP_RRC_SUB_SysInfoType1 (uint8_t(17))
#define GSMTAP_RRC_SUB_SysInfoType2 (uint8_t(18))
#define GSMTAP_RRC_SUB_SysInfoType3 (uint8_t(19))
#define GSMTAP_RRC_SUB_SysInfoType4 (uint8_t(20))
#define GSMTAP_RRC_SUB_SysInfoType5 (uint8_t(21))
#define GSMTAP_RRC_SUB_SysInfoType5bis (uint8_t(22))
#define GSMTAP_RRC_SUB_SysInfoType6 (uint8_t(23))
#define GSMTAP_RRC_SUB_SysInfoType7 (uint8_t(24))
#define GSMTAP_RRC_SUB_SysInfoType8 (uint8_t(25))
#define GSMTAP_RRC_SUB_SysInfoType9 (uint8_t(26))
#define GSMTAP_RRC_SUB_SysInfoType10 (uint8_t(27))
#define GSMTAP_RRC_SUB_SysInfoType11 (uint8_t(28))
#define GSMTAP_RRC_SUB_SysInfoType11bis (uint8_t(29))
#define GSMTAP_RRC_SUB_SysInfoType12 (uint8_t(30))
#define GSMTAP_RRC_SUB_SysInfoType13 (uint8_t(31))
#define GSMTAP_RRC_SUB_SysInfoType13_1 (uint8_t(32))
#define GSMTAP_RRC_SUB_SysInfoType13_2 (uint8_t(33))
#define GSMTAP_RRC_SUB_SysInfoType13_3 (uint8_t(34))
#define GSMTAP_RRC_SUB_SysInfoType13_4 (uint8_t(35))
#define GSMTAP_RRC_SUB_SysInfoType14 (uint8_t(36))
#define GSMTAP_RRC_SUB_SysInfoType15 (uint8_t(37))
#define GSMTAP_RRC_SUB_SysInfoType15bis (uint8_t(38))
#define GSMTAP_RRC_SUB_SysInfoType15_1 (uint8_t(39))
#define GSMTAP_RRC_SUB_SysInfoType15_1bis (uint8_t(40))
#define GSMTAP_RRC_SUB_SysInfoType15_2 (uint8_t(41))
#define GSMTAP_RRC_SUB_SysInfoType15_2bis (uint8_t(42))
#define GSMTAP_RRC_SUB_SysInfoType15_2ter (uint8_t(43))
#define GSMTAP_RRC_SUB_SysInfoType15_3 (uint8_t(44))
#define GSMTAP_RRC_SUB_SysInfoType15_3bis (uint8_t(45))
#define GSMTAP_RRC_SUB_SysInfoType15_4 (uint8_t(46))
#define GSMTAP_RRC_SUB_SysInfoType15_5 (uint8_t(47))
#define GSMTAP_RRC_SUB_SysInfoType15_6 (uint8_t(48))
#define GSMTAP_RRC_SUB_SysInfoType15_7 (uint8_t(49))
#define GSMTAP_RRC_SUB_SysInfoType15_8 (uint8_t(50))
#define GSMTAP_RRC_SUB_SysInfoType16 (uint8_t(51))
#define GSMTAP_RRC_SUB_SysInfoType17 (uint8_t(52))
#define GSMTAP_RRC_SUB_SysInfoType18 (uint8_t(53))
#define GSMTAP_RRC_SUB_SysInfoType19 (uint8_t(54))
#define GSMTAP_RRC_SUB_SysInfoType20 (uint8_t(55))
#define GSMTAP_RRC_SUB_SysInfoType21 (uint8_t(56))
#define GSMTAP_RRC_SUB_SysInfoType22 (uint8_t(57))
#define GSMTAP_RRC_SUB_SysInfoTypeSB1 (uint8_t(58))
#define GSMTAP_RRC_SUB_SysInfoTypeSB2 (uint8_t(59))
#define GSMTAP_RRC_SUB_ToTargetRNC_Container (uint8_t(60))
#define GSMTAP_RRC_SUB_TargetRNC_ToSourceRNC_Container (uint8_t(61))

#define GSMTAP_LTE_RRC_SUB_DL_CCCH_Message (uint8_t(0))
#define GSMTAP_LTE_RRC_SUB_DL_DCCH_Message (uint8_t(1))
#define GSMTAP_LTE_RRC_SUB_UL_CCCH_Message (uint8_t(2))
#define GSMTAP_LTE_RRC_SUB_UL_DCCH_Message (uint8_t(3))
#define GSMTAP_LTE_RRC_SUB_BCCH_BCH_Message (uint8_t(4))
#define GSMTAP_LTE_RRC_SUB_BCCH_DL_SCH_Message (uint8_t(5))
#define GSMTAP_LTE_RRC_SUB_PCCH_Message (uint8_t(6))
#define GSMTAP_LTE_RRC_SUB_MCCH_Message (uint8_t(7))

#define GSMTAP_LTE_RRC_SUB_BCCH_BCH_Message_MBMS (uint8_t(8))
#define GSMTAP_LTE_RRC_SUB_BCCH_DL_SCH_Message_BR (uint8_t(9))
#define GSMTAP_LTE_RRC_SUB_BCCH_DL_SCH_Message_MBMS (uint8_t(10))
#define GSMTAP_LTE_RRC_SUB_SC_MCCH_Message (uint8_t(11))
#define GSMTAP_LTE_RRC_SUB_SBCCH_SL_BCH_Message (uint8_t(12))
#define GSMTAP_LTE_RRC_SUB_SBCCH_SL_BCH_Message_V2X (uint8_t(13))
#define GSMTAP_LTE_RRC_SUB_DL_CCCH_Message_NB (uint8_t(14))
#define GSMTAP_LTE_RRC_SUB_DL_DCCH_Message_NB (uint8_t(15))
#define GSMTAP_LTE_RRC_SUB_UL_CCCH_Message_NB (uint8_t(16))
#define GSMTAP_LTE_RRC_SUB_UL_DCCH_Message_NB (uint8_t(17))
#define GSMTAP_LTE_RRC_SUB_BCCH_BCH_Message_NB (uint8_t(18))
#define GSMTAP_LTE_RRC_SUB_BCCH_BCH_Message_TDD_NB (uint8_t(19))
#define GSMTAP_LTE_RRC_SUB_BCCH_DL_SCH_Message_NB (uint8_t(20))
#define GSMTAP_LTE_RRC_SUB_PCCH_Message_NB (uint8_t(21))
#define GSMTAP_LTE_RRC_SUB_SC_MCCH_Message_NB (uint8_t(22))

#define GSMTAP_LTE_NAS_PLAIN (uint8_t(0))

#endif